# Generated by Django 4.1.7 on 2023-04-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_resume_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_uploader',
            name='my_file',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='resume_uploader',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='pro'),
        ),
    ]
